### ISSUE TITLE
'QuaternionIntegrator' object has no attribute 'constraints'

### ISSUE THREAD

**Issue by hsyysy** [stochasticHydroTools/RotationalDiffusion#5]
When I try to run the example in 'multi_bodies/examples/Multi_Blob_Two_Rollers' with
`python multi_bodies.py --input-file inputfile_rollers.dat`
It says in 'quaternion_integrator/quaternion_integrator_multi_bodies.py'
line 1376
AttributeError: 'QuaternionIntegrator' object has no attribute 'constraints'

I checked quaternion_integrator_multi_bodies.py and find that in line 67 the constraints is None and there is a "return" before it.
Does this matter?

**Comment by fbusabiaga** [comment]
Hi, we have been adding new schemes to the code and we forgot to update this example.
I just updated the code and it should work now. Please, update the code and give it another try.

> I checked `quaternion_integrator_multi_bodies.py` and find that in line 67 the constraints is None and 
> there is a "return" before it.
> Does this matter?

That was a bug, it is fixed now, Thanks!

**Comment by hsyysy** [comment]
Thanks, it now works.
